# Generated by Django 5.1 on 2024-08-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WasteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('plastic_percentage', models.FloatField(blank=True, null=True)),
                ('metal_percentage', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
